name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true 

      - name: Setup Hugo
        env:
          HUGO_VERSION: 0.135.0
        run: |
          mkdir ~/hugo
          cd ~/hugo
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' 
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Makefile
        run: make site

      - name: FTP Deploy & Remote PHP Unzip
        uses: zdenecek/zip-ftp-php-unzip@v1.0.0
        with:
          zip_source: "public/*"
          ftp_host: ${{ secrets.FTP_SERVER }}
          ftp_user: ${{ secrets.FTP_LOGIN }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          ftp_remote_path: "./"
          php_script_url: "https://bridge.zdenektomis.eu"

      # - name: Upload via FTP
      #   uses: airvzxf/ftp-deployment-action@latest
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     user: ${{ secrets.FTP_LOGIN }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local_dir: "./public/"
      #     remote_dir: "./"
      #     delete: "true"